version: '2'

services:

  esn:
    container_name: esn
    image: daotl/esn:1.9.0-rc8
    volumes:
      - ./docker/config:/var/www/docker/config:ro
    ports:
      - "8080:8080"
    networks:
      - default
      - emaily
    expose:
      - 8080
    environment:
      - DOCKER_IP=mail.internetapi.cn
      - PROVISION=${PROVISION}
      - CONFIG_DIR=/var/www/docker/config
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_PROTOCOL=amqp
      - AMQP_USERNAME=guest
      - AMQP_PASSWORD=guest
      - WEB_HOST=openpaas.internetapi.cn
      - WEB_PORT=8080
      - DAV_SERVER_HOST=sabre
      - DAV_SERVER_PORT=80
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}
      - JMAP_SCHEME=https
      - JMAP_SERVER_HOST=${DOCKER_IP}
      - JMAP_SERVER_PORT=443
      - MAIL_BROWSER=false
      - SMTP_HOST=james
      - SMTP_PORT=25
      - JAMES_WEBADMIN_SCHEME=https
      - JAMES_WEBADMIN_HOST=${DOCKER_IP}
      - JAMES_WEBADMIN_PORT=8000
    links:
      - redis
      - mongo
      - rabbitmq
      - sabre
      - elasticsearch

  redis:
    container_name: esn_redis
    image: redis:6.2.5
    volumes:
      - openpaas_redis_data:/data
    # ports:
    #   - "6379:6379"
    expose:
      - 6379

  rabbitmq:
    container_name: esn_rabbitmq
    image: rabbitmq:3.9.5-management
    hostname: esn-rabbit
    volumes:
      - openpaas_rabbitmq_data:/var/lib/rabbitmq
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    expose:
      - 5672
      - 15672

  mongo:
    container_name: esn_mongo
    image: mongo:5.0.2
    volumes:
      - openpaas_mongo_data:/data/db
    # ports:
    #   - "27017:27017"
    expose:
      - 27017

  elasticsearch:
    container_name: esn_elasticsearch
    image: elasticsearch:7.14.1
    volumes:
      - openpaas_elasticsearch_data:/usr/share/elasticsearch/data
    # ports:
    #   - "9200:9200"
    expose:
      - 9200
    environment:
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}
      - discovery.type=single-node

  sabre:
    container_name: esn_sabre
    image: linagora/esn-sabre:1.9.0-rc8
    ports:
      - "8001:80"
    environment:
      - SABRE_MONGO_HOST=mongo
      - SABRE_MONGO_PORT=27017
      - ESN_MONGO_HOST=mongo
      - ESN_MONGO_PORT=27017
      - ESN_MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - ESN_HOST=esn
      - ESN_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
    links:
      - mongo
    volumes:
      - ${PWD}/docker/config/jwt/public:/var/www/config/esn.key.pub

  # james:
  #   container_name: esn_james
  #   image: linagora/tmail-backend:memory-0.4.0
  #   # hostname: open-paas.org
  #   depends_on:
  #     - esn # to have configuration ready in shared volume
  #   ports:
  #     - "1080:80"
  #     - "1025:25"
  #     - "1110:110"
  #     - "1143:143"
  #     - "1465:465"
  #     - "1587:587"
  #     - "1993:993"
  #     - "8000:8000"
  #   volumes:
  #     - ./docker/config/james:/root/conf
  #     - ./docker/config/jwt/public:/root/conf/jwt_publickey

volumes:
  openpaas_redis_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/redis/data
      o: bind
  openpaas_rabbitmq_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/rabbitmq/data
      o: bind
  openpaas_mongo_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/mongo/data
      o: bind
  openpaas_elasticsearch_data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/elasticsearch/data
      o: bind

networks:
  emaily:
    external: true
  web:
    external: true
